apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-web
  annotations:
    nginx.ingress.kubernetes.io/rewriter-target: /
spec:
  rules:
    - host: www.app-web.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: app-web
                port:
                  number: 3000
